baseURL = "https://rumiehappiness.com/"
languageCode = "ja"
title = "The best is yet to come."
paginate = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false
